[package]
name = "change_case"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen="0.2"
regex = "1.5.4"

[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = 3